extends Control


const four = ["That", "With", "This", "From", "Have", "They", "Were", "Been", "More", "When", "Will", "What", "Them", "Than", "Some", "Time", "Into", "Only", "Such", "Also", "Then", "Most", "Said", "Your", "Very", "Made", "Many", "Over", "Like", "Even", "Well", "Must", "Same", "Work", "Life", "Each", "Much", "Both", "Upon", "Used", "Part", "Good", "Make", "Long", "Just", "Here", "Does", "Down", "Case", "Back", "Know", "High", "Take", "Year", "Thus", "Form", "Come", "Less", "Last", "Left", "Fact", "Hand", "Came", "York", "Give", "Find", "Need", "Once", "Four", "Home", "Data", "Name", "Body", "City", "Book", "Side", "Away", "Best", "Line", "John", "Days", "Seen", "Land", "Head", "Took", "Went", "Mind", "Next", "View", "Five", "Love", "Area", "True", "Self", "Want", "Ever", "Free", "Done", "King", "Type"]

const five = ["Which", "Their", "There", "Would", "Other", "These", "About", "First", "Could", "After", "Those", "Where", "Being", "Under", "Years", "Great", "State", "World", "Three", "While", "Found", "Might", "Still", "Right", "Place", "Every", "Power", "Since", "Given", "Never", "Order", "Water", "Small", "Shall", "Large", "Point", "Again", "Often", "Among", "House", "Women", "Group", "Think", "Human", "Later", "Until", "Whole", "Early", "Means", "Above", "Value", "Study", "Table", "Taken", "Times", "Known", "Court", "Young", "Words", "White", "Light", "Least", "Level", "Child", "Death", "Press", "Cases", "Going", "Party", "Using", "Sense", "Based", "Whose", "South", "Total", "Class", "Local", "Along", "Terms", "Money", "Black", "Force", "North", "Night", "Short", "Field", "Asked", "Quite", "Thing", "Woman", "Major", "Third", "Shown", "Began", "Cause", "Heart", "Seems", "Trade", "Clear", "Model"]

const six = ["Should", "People", "Before", "During", "Little", "System", "Number", "States", "Social", "Within", "Public", "Called", "Second", "Though", "Always", "School", "Others", "United", "Family", "Figure", "Rather", "Course", "Things", "Nature", "Having", "Change", "Become", "Period", "Common", "Person", "Either", "Church", "Effect", "Around", "Better", "Itself", "Almost", "Action", "Father", "Making", "Result", "Matter", "Became", "London", "Policy", "Enough", "Mother", "Reason", "Health", "Theory", "Office", "Single", "Groups", "Method", "French", "Report", "Future", "Higher", "Amount", "Really", "Indeed", "Growth", "Market", "Energy", "Living", "Return", "Toward", "Strong", "Rights", "Letter", "Looked", "Seemed", "Ground", "Modern", "Moment", "Values", "Turned", "Across", "Middle", "Longer", "Spirit", "Simple", "Series", "Source", "Months", "Likely", "Behind", "Taking", "Object", "Twenty", "Income", "Beyond", "Design", "Except", "Latter", "Points", "Direct", "Manner", "Appear", "German"]

const seven = ["Between", "Through", "Because", "However", "Without", "General", "Another", "Against", "Present", "Example", "Himself", "Thought", "Country", "History", "Several", "Chapter", "Process", "Certain", "Control", "Whether", "Company", "Society", "Nothing", "Service", "Further", "Subject", "Problem", "Century", "Section", "Already", "Various", "English", "Perhaps", "Members", "Support", "Results", "Usually", "Special", "Similar", "Brought", "British", "Natural", "Account", "Changes", "Studies", "Greater", "Foreign", "England", "Working", "Surface", "Program", "Systems", "Central", "Provide", "Science", "Purpose", "America", "Current", "Believe", "Effects", "Written", "Private", "Percent", "Capital", "Finally", "Related", "Instead", "Outside", "Persons", "Patient", "Respect", "Culture", "Methods", "William", "College", "Friends", "Hundred", "Include", "Writing", "Council", "Disease", "Towards", "Average", "Carried", "Quality", "Morning", "Workers", "Journal", "Western", "Reading", "Species", "Looking", "Factors", "Earlier", "Appears", "Schools", "Meaning", "Opinion", "Becomes", "Limited"]

const eight = ["Children", "American", "Possible", "Although", "National", "Business", "Question", "Interest", "Economic", "Research", "Together", "Position", "Problems", "Language", "Analysis", "Evidence", "Required", "Students", "Probably", "Material", "Function", "Increase", "Personal", "Property", "Specific", "Practice", "Received", "Services", "Provided", "Movement", "Activity", "Building", "Anything", "Physical", "Approach", "Pressure", "Military", "Complete", "Followed", "Addition", "Industry", "Original", "Patients", "Standard", "Produced", "Decision", "Involved", "Solution", "Obtained", "Behavior", "Response", "Consider", "Learning", "Training", "Presence", "Expected", "Observed", "Actually", "Elements", "Religion", "European", "Security", "Distance", "Products", "Congress", "Directly", "Strength", "Relation", "Cultural", "Reported", "Appeared", "Included", "Thinking", "Instance", "Positive", "Whatever", "Thousand", "Remember", "Constant", "Returned", "Minister", "District", "Division", "Progress", "Remained", "Relative", "Previous", "Separate", "Planning", "Exchange", "Critical", "Marriage", "Programs", "Internal", "Politics", "December", "Teachers", "Prepared", "Continue", "Measures"]

const nine = ["Different", "Important", "Following", "Political", "Therefore", "Something", "Education", "Necessary", "Knowledge", "According", "Sometimes", "Community", "Including", "Structure", "Available", "Treatment", "Character", "President", "Countries", "Generally", "Influence", "Situation", "Described", "Difficult", "Attention", "Continued", "Increased", "Questions", "Committee", "Developed", "Religious", "Authority", "Condition", "Beginning", "Relations", "Published", "Christian", "Direction", "Operation", "Effective", "Resources", "Certainly", "Principle", "Materials", "Potential", "Presented", "Statement", "Financial", "Existence", "Reference", "Interests", "Mentioned", "Concerned", "Agreement", "Processes", "Functions", "Discussed", "September", "Essential", "Otherwise", "Determine", "Companies", "Suggested", "Expressed", "Principal", "Practical", "Beautiful", "Formation", "Procedure", "Secretary", "Equipment", "Advantage", "Technical", "Spiritual", "Standards", "Professor", "Tradition", "Frequency", "Institute", "Decisions", "Performed", "Indicated", "Represent", "Explained", "Immediate", "Connected", "Secondary", "Americans", "Insurance", "Carefully", "Selection", "Employees", "Cambridge", "Appointed", "Contained", "Increases", "Supported", "Movements", "Establish", "Extremely"]

const ten = ["Government", "University", "Themselves", "Individual", "Particular", "Experience", "Conditions", "Especially", "Production", "Considered", "Population", "Management", "Department", "Activities", "Understand", "Difference", "Importance", "Associated", "Everything", "Washington", "Throughout", "Discussion", "Determined", "Literature", "Principles", "Expression", "Historical", "Industrial", "Commission", "Frequently", "Additional", "Sufficient", "Technology", "Scientific", "Protection", "Completely", "Successful", "Increasing", "Impossible", "Revolution", "Philosophy", "Relatively", "Employment", "Operations", "Connection", "Collection", "Appearance", "Resistance", "California", "Properties", "Conference", "Investment", "Commercial", "Introduced", "Concerning", "Understood", "Definition", "Difficulty", "Conclusion", "Techniques", "Apparently", "Structures", "Comparison", "Developing", "Containing", "Generation", "Discovered", "Recognized", "Interested", "Proportion", "Previously", "Assistance", "Parliament", "Foundation", "Opposition", "Democratic", "Background", "Provisions", "Components", "Identified", "Evaluation", "Leadership", "Procedures", "References", "Confidence", "Assessment", "Characters", "Reasonable", "Subsequent", "Convention", "Resolution", "Eventually", "Psychology", "Represents", "Experiment", "Statements", "Possession", "Settlement", "Controlled", "Maintained"]

const all = [four, five, six, seven, eight, nine, ten]

var speed = 0

var started = 0

func _ready():
	pass # Replace with function body.


# Called every frame. 'delta' is the elapsed time since the previous frame.
#func _process(delta):
#	pass
